title: "আমার বাংলা ব্লগ"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # এখানে air, aqua, contrast বা dirt ব্যবহার করতে পারেন

url: "https://mdarafathosentop.github.io/My-blog" # এখানে আপনার ইউজারনেম দিন
baseurl: ""

repository: "yourusername/your-repo-name" # আপনার ইউজারনেম/রিপোজিটরির নাম দিন

plugins:
  - jekyll-include-cache
  - jekyll-sitemap

include:
  - _pages
author:
  name   : "Md Arafat Hosen"
  bio    : "আমি একজন ব্লগার এবং প্রযুক্তি প্রেমী।"
  avatar : "assets/images/bio-photo.jpg" # পরে এই নামে ছবি আপলোড করবেন
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/yourprofile"
      url: "https://mdarafathosentop.github.io"
baseurl: "/My-blog"
paginate: 5
paginate_path: /page:num/
